######################################################################
# Automatically generated by qmake (3.0) ?? 12. ??? 10:00:44 2013
######################################################################

TEMPLATE = app
TARGET = stikers
INCLUDEPATH += .
CONFIG += console qaxcontainer
QT += core printsupport
QT -= gui 
# LIBS += lqaxcontainer

# Input
SOURCES += main.cpp
